### PR TITLE
Xiangwei

### PR DESCRIPTION
**Pull request by caxian**

### CODE REVIEW

**Comment by caxian** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/caxian/XiangweiOPSTest, working directory: W:\lsjp-s, target branch: master, target branch commit: 1e0f324cc8630a4178a6a00b558ccf7928368473, source branch: xiangwei, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C27%5Cdfcca464-89ef-3cae-31b4-6e0779477817%5CPullRequest%5C201711270523468850-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mMvDNZlCqWcs5X7EjWlqvA48krHdzuHLytcflhd8QRM%3D&st=2017-11-27T05%3A18%3A52Z&se=2017-12-28T05%3A23%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by caxian** [comment]
#sign-off

**Comment by PRMerger15** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by caxian** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/caxian/XiangweiOPSTest, working directory: W:\s5co-s, target branch: master, target branch commit: 1e0f324cc8630a4178a6a00b558ccf7928368473, source branch: xiangwei, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C27%5Cdfcca464-89ef-3cae-31b4-6e0779477817%5CPullRequest%5C201711270600367722-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D56jm0x1d2%2BBuMGfbemTNQq%2FeZ%2FHNT2dkByg7QQdz7k%3D&st=2017-11-27T05%3A55%3A41Z&se=2017-12-28T06%3A00%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by caxian** [comment]
### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C27%5Cdfcca464-89ef-3cae-31b4-6e0779477817%5CPullRequest%5C201711270603134741-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8UQmrI5GLnYQ8GWe2VkNUnD97N8rl6FougACO2saSNk%3D&st=2017-11-27T05%3A58%3A47Z&se=2017-12-28T06%3A03%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by caxian** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset/Test.md](https://github.com/caxian/XiangweiOPSTest/blob/xiangwei/Docset/Test.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C27%5Cdfcca464-89ef-3cae-31b4-6e0779477817%5CPullRequest%5C201711270610019422-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=opQkVQCmqTqRQ%2BGazIx3ib%2FO%2FEp76lIy7PcQBd32URw%3D&st=2017-11-27T06%3A05%3A37Z&se=2017-12-28T06%3A10%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by caxian** [comment]
#sign-off

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by caxian** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by caxian** [comment]
#sign-off

**Comment by caxian** [comment]
#hold-off

**Pull request merged**
